#!/bin/bash
if ! [ -d ~/.aws-profile/ ] ; then
	script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	if ! [ -f "${script_dir}/aws-profile.sh" ] ; then
		# Download aws-profile from github
		git clone https://github.com/bytebutcher/aws-profile ~/.aws-profile/
	else
		# Copy from filesystem
		mkdir ~/.aws-profile/
		cp "${script_dir}/aws-profile.sh" ~/.aws-profile/
	fi
fi

if ! [ -f ~/.aws-profile/aws-profile.sh ] ; then
	echo "ERROR: Installation of aws-profile failed!" >&2
	exit 1
fi

cat <<EOF > ~/.aws-profile.bash
unalias aws-profile 2> /dev/null
aws-profile() {
	case "\${1}" in
		use )
			if ~/.aws-profile/aws-profile.sh \$@ > /dev/null; then
				echo "export AWS_PROFILE=\"\${2}\"" > ~/.aws-profile/current
				source ~/.aws-profile/current &> /dev/null
				aws configure list
				return 0
			fi
			return 1
			;;
		reload )
			source ~/.aws-profile/current &> /dev/null
			;;
		* )
			aws-profile.sh \$@
			;;
	esac
}
export -f aws-profile &> /dev/null
export PATH=~/.aws-profile/:\${PATH}
source ~/.aws-profile/current &> /dev/null
EOF

if ! [ -f ~/.aws-profile.bash ] ; then
	echo "ERROR: Installation of aws-profile failed!" >&2
	exit 1
fi

if ! grep "\[ -f ~/.aws-profile.bash \] && source ~/.aws-profile.bash" ~/.bashrc > /dev/null; then 
	echo "[ -f ~/.aws-profile.bash ] && source ~/.aws-profile.bash" >> ~/.bashrc
fi

echo "Finished. Restart your shell or reload config file."
[[ "$shells" =~ bash ]] && echo "   source ~/.bashrc  # bash"
#[[ "$shells" =~ zsh ]]  && echo "   source ${ZDOTDIR:-~}/.zshrc   # zsh"
#[[ "$shells" =~ fish ]] && [ $key_bindings -eq 1 ] && echo "   fzf_key_bindings  # fish"
exit 0
