#!/bin/bash
function do_require_command() {
        local required_command="${1}"
        command -v "${required_command}" >/dev/null 2>&1 || {
                print_error "Require ${required_command} but it's not installed. Aborting."
                exit 1;
        }
}

do_require_command "git"
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if ! [ -f "${script_dir}/aws-profile.sh" ] ; then
	if ! [ -d ~/.aws-profile/.git ] ; then
		echo "Installing aws-profile via github..." >&2
		git clone https://github.com/bytebutcher/aws-profile ~/.aws-profile/
	else
		echo "Updating aws-profile via github..." >&2
		(cd ~/.aws-profile && git pull)
	fi
else
	mkdir -p ~/.aws-profile/
	if ! [ -f ~/.aws-profile/aws-profile.sh ] ; then
		echo "Installing aws-profile..." >&2
		cp "${script_dir}/aws-profile.sh" ~/.aws-profile/
	else
		echo "Updating aws-profile..." >&2
		cp "${script_dir}/aws-profile.sh" ~/.aws-profile/
	fi
fi

if ! [ -f ~/.aws-profile/aws-profile.sh ] ; then
	echo "ERROR: Installation of aws-profile failed!" >&2
	exit 1
fi

cat <<EOF > ~/.aws-profile.bash
unalias aws-profile 2> /dev/null
aws-profile() {
	case "\${1}" in
		use )
			if ~/.aws-profile/aws-profile.sh \$@ > /dev/null; then
				echo "export AWS_PROFILE=\"\${2}\"" > ~/.aws-profile/current
				source ~/.aws-profile/current &> /dev/null
				aws configure list
				return 0
			fi
			return 1
			;;
		reload )
			source ~/.aws-profile/current &> /dev/null
			;;
		* )
			aws-profile.sh \$@
			;;
	esac
}
export -f aws-profile &> /dev/null
export PATH=~/.aws-profile/:\${PATH}
source ~/.aws-profile/current &> /dev/null
EOF

if ! [ -f ~/.aws-profile.bash ] ; then
	echo "ERROR: Installation of aws-profile failed!" >&2
	exit 1
fi

if ! grep "\[ -f ~/.aws-profile.bash \] && source ~/.aws-profile.bash" ~/.bashrc > /dev/null; then 
	echo "[ -f ~/.aws-profile.bash ] && source ~/.aws-profile.bash" >> ~/.bashrc
fi

echo "Finished. Restart your shell or reload config file." >&2
[[ "$shells" =~ bash ]] && echo "   source ~/.bashrc  # bash"
#[[ "$shells" =~ zsh ]]  && echo "   source ${ZDOTDIR:-~}/.zshrc   # zsh"
#[[ "$shells" =~ fish ]] && [ $key_bindings -eq 1 ] && echo "   fzf_key_bindings  # fish"
exit 0
